OPS-6646: Allow defining subnet ACL rules
HeadspaceMeditation/terraform-aws-dynamic-subnets pull request #1
Opened 2021-06-01 22:23 UTC by cheethoe

So we can pass ACL rules directly into the module.

2021-06-01 22:30 UTC, parkedwards commented on private.tf
> +#### updated
for...?

2021-06-01 22:31 UTC, cheethoe commented on private.tf
> +#### updated
I think he just put that there to show where he added stuff

2021-06-01 22:31 UTC, cheethoe commented on private.tf
> +#### updated
I'll just remove those comments

2021-06-01 22:33 UTC, parkedwards submitted a review, later dismissed

2021-06-01 22:34 UTC, cheethoe commented on variables.tf
> +variable "local_public_nacl_rules" {
how are these local?

2021-06-01 22:35 UTC, cheethoe commented on variables.tf
> +variable "local_public_nacl_rules" {
can we get rid of the `local_` prefix?

2021-06-01 22:35 UTC, cheethoe commented on variables.tf
> +variable "local_public_nacl_rules" {
@dvhoang-amazon

2021-06-01 22:38 UTC, mrwacky42 commented on private.tf
> +resource "aws_network_acl" "private_secure_nacl" {
1) This looks like all rules are ingress and egress at the same time?
2) This will end up leaving the old icky default open NACLs lying around which #feelsbadman
Perhaps we should add the new variables with the default "OPEN" rules, and convert the existing NACLs to be dynamic?
3) Cloudposse has https://github.com/cloudposse/terraform-aws-named-subnets which solves this problem.. I think we should airlift their version, which also supports ICMP/ipv6 if we need it.

2021-06-01 22:50 UTC, mrwacky42 requested changes
See my comment

2021-06-02 19:09 UTC, dvhoang-amazon commented on private.tf
> +resource "aws_network_acl" "private_secure_nacl" {
Updated - split the ingress and egresss and allowed the icmp options.  Please review

2021-06-02 19:43 UTC, dvhoang-amazon commented on variables.tf
> +variable "local_public_nacl_rules" {
Updated the naming, please review.

2021-06-02 20:39 UTC, cheethoe commented on variables.tf
> +variable "local_public_nacl_rules" {
names look better

2021-06-02 20:40 UTC, cheethoe reviewed
in terms if this specific module, lgtm.  However I don't have approve powers in this case.

2021-06-03 17:25 UTC, mrwacky42 commented on private.tf
> +      icmp_type  = egress.value["icmp_type"]
I think these all need defaults.
like:
```
      action          = lookup(egress.value, "action", null)
```

2021-06-03 17:28 UTC, mrwacky42 commented on private.tf
> +      icmp_type  = egress.value["icmp_type"]
OR: we can't set the defaults in variables.tf and need to ensure that callers that get updated to this new version set the legacy defaults.

2021-06-03 22:43 UTC, mrwacky42 approved these changes
Future work to change ergonomics and not expect callers to pass in `null` values.

2021-06-04 00:12 UTC, merged